// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxZ4WriBnOClcFZPBT28cp6f7fDAU7MCE',
    appId: '1:526557775811:web:beac17ce531453d3965f76',
    messagingSenderId: '526557775811',
    projectId: 'task-data-9e226',
    authDomain: 'task-data-9e226.firebaseapp.com',
    storageBucket: 'task-data-9e226.firebasestorage.app',
    measurementId: 'G-N2NCD9LVQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWFX_ZOyZjSIpFakqsvcYZ5u_a8Ky-b0',
    appId: '1:526557775811:android:5fcb065441abf823965f76',
    messagingSenderId: '526557775811',
    projectId: 'task-data-9e226',
    storageBucket: 'task-data-9e226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYSaronXJVIHdWNp5yfJ3stVZXcwEdls',
    appId: '1:526557775811:ios:679d1b02dfbf3f7c965f76',
    messagingSenderId: '526557775811',
    projectId: 'task-data-9e226',
    storageBucket: 'task-data-9e226.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYSaronXJVIHdWNp5yfJ3stVZXcwEdls',
    appId: '1:526557775811:ios:679d1b02dfbf3f7c965f76',
    messagingSenderId: '526557775811',
    projectId: 'task-data-9e226',
    storageBucket: 'task-data-9e226.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxZ4WriBnOClcFZPBT28cp6f7fDAU7MCE',
    appId: '1:526557775811:web:f84aba5c89865906965f76',
    messagingSenderId: '526557775811',
    projectId: 'task-data-9e226',
    authDomain: 'task-data-9e226.firebaseapp.com',
    storageBucket: 'task-data-9e226.firebasestorage.app',
    measurementId: 'G-MP6J1KZEH1',
  );
}
